/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void draw_controls(PApplet appc, GWinData data) { //_CODE_:controls:681939:
  appc.background(230);
} //_CODE_:controls:681939:

public void intersection_click(GDropList source, GEvent event) { //_CODE_:typeOfIntersection:616857:
  println("typeOfIntersection - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:typeOfIntersection:616857:

public void inflow_change(GCustomSlider source, GEvent event) { //_CODE_:inflow_slider:484929:
  println("inflow_slider - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:inflow_slider:484929:

public void aggression_change(GCustomSlider source, GEvent event) { //_CODE_:aggression_slider:810211:
  println("aggression_slider - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:aggression_slider:810211:

public void cars_change(GCustomSlider source, GEvent event) { //_CODE_:cars_slider:329200:
  println("cars_slider - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:cars_slider:329200:

public void trucks_change(GCustomSlider source, GEvent event) { //_CODE_:trucks_slider:463589:
  println("trucks_slider - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:trucks_slider:463589:

public void transport_change(GCustomSlider source, GEvent event) { //_CODE_:transport_slider:569098:
  println("transport_slider - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:transport_slider:569098:

public void speed_change(GCustomSlider source, GEvent event) { //_CODE_:speed_slider:460307:
  println("speed_slider - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:speed_slider:460307:

public void acceleration_change(GCustomSlider source, GEvent event) { //_CODE_:acceleration_slider:554804:
  println("acceleration_slider - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:acceleration_slider:554804:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:dropList1:960909:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropList1:960909:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  controls = GWindow.getWindow(this, "GUI controls", 0, 0, 330, 370, JAVA2D);
  controls.noLoop();
  controls.setActionOnClose(G4P.KEEP_OPEN);
  controls.addDrawHandler(this, "draw_controls");
  intersection_label = new GLabel(controls, 16, 12, 117, 20);
  intersection_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  intersection_label.setText("Type of Intersection");
  intersection_label.setOpaque(false);
  typeOfIntersection = new GDropList(controls, 16, 34, 119, 60, 2, 10);
  typeOfIntersection.setItems(loadStrings("list_616857"), 0);
  typeOfIntersection.addEventHandler(this, "intersection_click");
  inflow_rate = new GLabel(controls, 201, 11, 97, 19);
  inflow_rate.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  inflow_rate.setText("Car Inflow Rate");
  inflow_rate.setOpaque(false);
  inflow_slider = new GCustomSlider(controls, 200, 23, 100, 40, "grey_blue");
  inflow_slider.setLimits(40, 10, 100);
  inflow_slider.setNumberFormat(G4P.INTEGER, 0);
  inflow_slider.setOpaque(false);
  inflow_slider.addEventHandler(this, "inflow_change");
  aggression_level = new GLabel(controls, 201, 72, 107, 17);
  aggression_level.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  aggression_level.setText("Aggression Level");
  aggression_level.setOpaque(false);
  aggression_slider = new GCustomSlider(controls, 202, 81, 100, 40, "grey_blue");
  aggression_slider.setLimits(3.0, 1.0, 10.0);
  aggression_slider.setNumberFormat(G4P.DECIMAL, 2);
  aggression_slider.setOpaque(false);
  aggression_slider.addEventHandler(this, "aggression_change");
  vehicle_label = new GLabel(controls, 14, 100, 147, 20);
  vehicle_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  vehicle_label.setText("Vehicle Type Percentages");
  vehicle_label.setOpaque(false);
  cars_label = new GLabel(controls, 45, 126, 80, 20);
  cars_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  cars_label.setText("Cars %");
  cars_label.setOpaque(false);
  cars_slider = new GCustomSlider(controls, 33, 144, 100, 40, "DECIMAL");
  cars_slider.setLimits(60, 0, 100);
  cars_slider.setNumberFormat(G4P.INTEGER, 0);
  cars_slider.setOpaque(false);
  cars_slider.addEventHandler(this, "cars_change");
  trucks_label = new GLabel(controls, 42, 188, 80, 20);
  trucks_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  trucks_label.setText("Trucks %");
  trucks_label.setOpaque(false);
  trucks_slider = new GCustomSlider(controls, 31, 205, 100, 40, "grey_blue");
  trucks_slider.setLimits(10, 0, 100);
  trucks_slider.setNumberFormat(G4P.INTEGER, 0);
  trucks_slider.setOpaque(false);
  trucks_slider.addEventHandler(this, "trucks_change");
  transport_label = new GLabel(controls, 26, 249, 113, 20);
  transport_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  transport_label.setText("Public Transport %");
  transport_label.setOpaque(false);
  transport_slider = new GCustomSlider(controls, 31, 269, 100, 40, "grey_blue");
  transport_slider.setLimits(30, 0, 100);
  transport_slider.setNumberFormat(G4P.INTEGER, 0);
  transport_slider.setOpaque(false);
  transport_slider.addEventHandler(this, "transport_change");
  speed_limit = new GLabel(controls, 204, 124, 80, 20);
  speed_limit.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  speed_limit.setText("Speed Limit");
  speed_limit.setOpaque(false);
  speed_slider = new GCustomSlider(controls, 200, 145, 100, 40, "grey_blue");
  speed_slider.setLimits(50, 20, 100);
  speed_slider.setNumberFormat(G4P.INTEGER, 0);
  speed_slider.setOpaque(false);
  speed_slider.addEventHandler(this, "speed_change");
  acceleration_label = new GLabel(controls, 203, 188, 101, 20);
  acceleration_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  acceleration_label.setText("Max Acceleration");
  acceleration_label.setOpaque(false);
  acceleration_slider = new GCustomSlider(controls, 201, 203, 100, 40, "grey_blue");
  acceleration_slider.setLimits(40, 10, 100);
  acceleration_slider.setNumberFormat(G4P.INTEGER, 0);
  acceleration_slider.setOpaque(false);
  acceleration_slider.addEventHandler(this, "acceleration_change");
  weather_label = new GLabel(controls, 201, 251, 80, 20);
  weather_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  weather_label.setText("Weather");
  weather_label.setOpaque(false);
  dropList1 = new GDropList(controls, 197, 274, 90, 80, 3, 10);
  dropList1.setItems(loadStrings("list_960909"), 0);
  dropList1.addEventHandler(this, "dropList1_click1");
  controls.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow controls;
GLabel intersection_label; 
GDropList typeOfIntersection; 
GLabel inflow_rate; 
GCustomSlider inflow_slider; 
GLabel aggression_level; 
GCustomSlider aggression_slider; 
GLabel vehicle_label; 
GLabel cars_label; 
GCustomSlider cars_slider; 
GLabel trucks_label; 
GCustomSlider trucks_slider; 
GLabel transport_label; 
GCustomSlider transport_slider; 
GLabel speed_limit; 
GCustomSlider speed_slider; 
GLabel acceleration_label; 
GCustomSlider acceleration_slider; 
GLabel weather_label; 
GDropList dropList1; 
